version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 3s
      timeout: 2s
      retries: 5

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    command: >
      sh -c "pnpm prisma migrate deploy && pnpm build:main && pnpm start:prod:main"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - ACCESS_SECRET=access_secret
      - REFRESH_SECRET=refresh_secret
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    command: >
      sh -c "pnpm prisma migrate deploy && pnpm build:admin && pnpm start:prod:admin"
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - ACCESS_SECRET=access_secret
      - REFRESH_SECRET=refresh_secret
      - PORT=3001
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
