version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    command: >
      sh -c "pnpm start:prod:main"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    command: >
      sh -c "pnpm start:prod:admin"
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT=3001
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
