version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 3s
      timeout: 2s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pnpm prisma migrate reset --force && pnpm concurrently \"nest start main\" \"nest start admin\""
    ports:
      - '${PORT}:${PORT}'
      - '${PORT_ADMIN}:${PORT_ADMIN}'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - ACCESS_SECRET=access_secret
      - REFRESH_SECRET=refresh_secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
