version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    command: >
      sh -c "pnpm start:prod:main"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT=3000
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    command: >
      sh -c "pnpm start:prod:admin"
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT_ADMIN=3001
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
