name: Deploy Admin

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'apps/main/**'
      - '.github/workflows/deploy_main.yaml'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm i -g pnpm && pnpm install

      - name: Run test
        run: pnpm test 


  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.admin
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/admin:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}
            REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
          cache-from: type=gha


  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Wait for main deploy
        run: sleep 60

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin:latest


            docker stop admin || true
            docker rm admin || true

            docker run -d --name admin \
              -p ${{ secrets.PORT_ADMIN }}:${{ secrets.PORT_ADMIN }} \
              --restart unless-stopped \
              -e NODE_ENV=production \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e ACCESS_SECRET=${{ secrets.ACCESS_SECRET }} \
              -e REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} \
              -e PORT_ADMIN=${{ secrets.PORT_ADMIN }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/admin:latest


